fix(test): execution des test avec maven
GL2-GR5/kakuro pull request #69
Opened 2024-03-28 14:17 UTC by meo-pill

+lisibilité

2024-03-28 15:41 UTC, ABTonniere requested changes

2024-03-28 15:41 UTC, ABTonniere commented on src/main/java/fr/mcgcorp/managers/SaveManager.java
Pas de commentaire

2024-03-28 15:41 UTC, ABTonniere commented on src/main/resources/fr/mcgcorp/anotherTest.json
à supprimer je pense (Je peux pas faire de à en majuscule sur windows)

2024-03-28 15:41 UTC, ABTonniere commented on src/main/java/fr/mcgcorp/managers/JsonFile.java
Review générale pour dire qu'il y a des fautes d'orthographe dans les commentaires

2024-03-28 17:14 UTC, meo-pill commented on src/main/java/fr/mcgcorp/managers/JsonFile.java
je ferai les faute a un autre moment

2024-03-28 17:18 UTC, meo-pill commented on src/main/resources/fr/mcgcorp/anotherTest.json
on vera plus tard pour le moment on peut pas faire sans

2024-03-28 17:18 UTC, meo-pill commented on src/main/java/fr/mcgcorp/managers/SaveManager.java
fait

2024-03-28 17:19 UTC, meo-pill commented
Attendre que save-manager-erwan soit fini

2024-03-29 09:57 UTC, ABTonniere requested changes

2024-03-29 09:57 UTC, ABTonniere commented on src/test/java/fr/mcgcorp/managers/JsonFileTest.java
> +   * Tout les attribut de cette classes doivent-être accessible, a moins de
"attribut**s**", "classe" sans **s**, "**à** moins"

2024-03-29 10:02 UTC, ABTonniere approved these changes

2024-03-29 10:03 UTC, merged