Develop
GL2-GR5/kakuro pull request #83
Opened 2024-04-02 16:33 UTC by meo-pill

2024-04-02 16:41 UTC, ABTonniere requested changes

2024-04-02 16:41 UTC, ABTonniere commented on src/main/java/fr/mcgcorp/fxml/controllers/Controller.java
> + * Classe abstraite qui représente un contrôleur graphique d'une interface plein ecran simple.
écran

2024-04-02 16:57 UTC, ABTonniere approved these changes, later dismissed

2024-04-03 07:33 UTC, meo-pill commented on src/main/java/fr/mcgcorp/managers/OsManager.java
>       * La clé du type de système d'exploitation.
les clés

2024-04-03 07:33 UTC, meo-pill commented on src/main/java/fr/mcgcorp/fxml/controllers/MenuController.java
> + * @author POURCEAU Luca
@see Interact ?

2024-04-03 07:33 UTC, meo-pill commented on src/main/java/fr/mcgcorp/fxml/controllers/HowToPlayController.java
> +   * @return une interface graphique de comment jouer.
un saut a la ligne avant les **@** et pas de saut a la ligne entre eux

2024-04-10 13:20 UTC, meo-pill commented on src/main/java/fr/mcgcorp/fxml/controllers/ProfileController.java
> +    f.getRoot().getStylesheets().add("fr/mcgcorp/fxml/styles/style.css");
style controleur ?

2024-04-16 10:15 UTC, merged